version: "2"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "microservice"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - '3306:3306'
    volumes:
      - database-mysql:/var/lib/mysql
volumes:
  database-mysql: