# Spring Boot configuração para perfil "dev".

logging:
  level:
    ROOT: INFO
spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
zuul:
  routes:
    microservice:
      path: /microservice/**
      service-id: microservice
      strip-prefix: false
      custom-sensitive-headers: true
