# Spring Boot configuração para perfil "dev".

logging:
  level:
    ROOT: INFO
spring:
  application:
    name: registry

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
  server:
    enable-self-preservation: false