# Spring Boot configuração para perfil "dev".

logging:
  level:
    ROOT: INFO

spring:
  application:
    name: microservice
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/microservice}
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081
  servlet:
    context-path: /microservice

eureka:
  instance:
    hostname: localhost
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
